-- ==========================================
-- 🚀 Supabase 데이터베이스 전체 설정
-- ==========================================
-- 
-- 📋 사용 방법:
-- 1. Supabase 대시보드 접속
-- 2. 왼쪽 메뉴에서 "SQL Editor" 클릭
-- 3. 이 파일의 전체 내용을 복사하여 붙여넣기
-- 4. "Run" 버튼 클릭
-- 
-- ⚠️ 주의: 이미 테이블이 있어도 안전하게 실행됩니다 (IF NOT EXISTS 사용)
-- ==========================================

-- ==========================================
-- 1️⃣ posts 테이블 (게시물)
-- ==========================================
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author_email TEXT NOT NULL,
    author_nickname TEXT,
    user_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- author_nickname 컬럼 추가 (이미 있으면 무시)
ALTER TABLE posts ADD COLUMN IF NOT EXISTS author_nickname TEXT;

-- ==========================================
-- 2️⃣ comments 테이블 (댓글)
-- ==========================================
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    author_email TEXT NOT NULL,
    author_nickname TEXT,
    user_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- author_nickname 컬럼 추가 (이미 있으면 무시)
ALTER TABLE comments ADD COLUMN IF NOT EXISTS author_nickname TEXT;

-- ==========================================
-- 3️⃣ profiles 테이블 (사용자 프로필)
-- ==========================================
CREATE TABLE IF NOT EXISTS profiles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    nickname TEXT NOT NULL,
    bio TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- bio 컬럼 추가 (이미 있으면 무시)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio TEXT;

-- user_id에 인덱스 생성 (빠른 조회)
CREATE INDEX IF NOT EXISTS profiles_user_id_idx ON profiles(user_id);

-- ==========================================
-- 4️⃣ RLS (Row Level Security) 활성화
-- ==========================================
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5️⃣ posts 테이블 보안 정책
-- ==========================================
-- 기존 정책 삭제 후 재생성
DROP POLICY IF EXISTS "Anyone can read posts" ON posts;
CREATE POLICY "Anyone can read posts" ON posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create posts" ON posts;
CREATE POLICY "Authenticated users can create posts" ON posts
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own posts" ON posts;
CREATE POLICY "Users can update own posts" ON posts
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own posts" ON posts;
CREATE POLICY "Users can delete own posts" ON posts
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 6️⃣ comments 테이블 보안 정책
-- ==========================================
DROP POLICY IF EXISTS "Anyone can read comments" ON comments;
CREATE POLICY "Anyone can read comments" ON comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create comments" ON comments;
CREATE POLICY "Authenticated users can create comments" ON comments 
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Users can delete comments" ON comments;
CREATE POLICY "Users can delete comments" ON comments 
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 7️⃣ profiles 테이블 보안 정책
-- ==========================================
DROP POLICY IF EXISTS "프로필 조회 허용" ON profiles;
CREATE POLICY "프로필 조회 허용" ON profiles
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "본인 프로필 생성 허용" ON profiles;
CREATE POLICY "본인 프로필 생성 허용" ON profiles
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "본인 프로필 수정 허용" ON profiles;
CREATE POLICY "본인 프로필 수정 허용" ON profiles
    FOR UPDATE USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "본인 프로필 삭제 허용" ON profiles;
CREATE POLICY "본인 프로필 삭제 허용" ON profiles
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 8️⃣ updated_at 자동 갱신 트리거
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- posts 테이블 트리거
DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
    BEFORE UPDATE ON posts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- profiles 테이블 트리거
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- ✅ 설정 완료!
-- ==========================================
-- 
-- 📊 생성된 테이블:
-- - posts (게시물)
-- - comments (댓글)
-- - profiles (사용자 프로필)
--
-- 🔒 보안 정책 (RLS) 적용됨
-- ⚡ 자동 갱신 트리거 적용됨
--
-- ==========================================
